compile:
	$(MAKE) -C lib
	$(MAKE) -C timed
	$(MAKE) -C timedc

install:
	$(MAKE) -C lib install
	$(MAKE) -C timed install
	$(MAKE) -C timedc install

clean:
	$(MAKE) -C lib clean
	$(MAKE) -C timed clean
	$(MAKE) -C timedc clean
