compile:
	(cd lib && $(MAKE))
	(cd timed && $(MAKE))
	(cd timedc && $(MAKE))

install:
	(cd lib && $(MAKE) install)
	(cd timed && $(MAKE) install)
	(cd timedc && $(MAKE) install)

clean:
	(cd lib && $(MAKE) clean)
	(cd timed && $(MAKE) clean)
	(cd timedc && $(MAKE) clean)
